In [28]:
import os

In [29]:
import numpy as np

In [30]:
np.random.seed(seed=0)
X = np.random.choice([0,1], 2)
W = np.random.choice([-1,1], 2)
print(f'Input vector:{X}, Weight vector:{W}')

Input vector:[0 1], Weight vector:[ 1 -1]


In [31]:
dot = X @ W
print(f'Dot product: {dot}')

Dot product: -1


In [32]:
def linear_threshold_gate(dot: int, T: float) -> int:
    '''Returns the binary threshold output'''
    if dot >= T:
        return 1
    else:
        return 0

In [33]:
T = -1
activation = linear_threshold_gate(dot, T)
print(f'Activation: {activation}')

Activation: 1


In [34]:
T = 0
activation = linear_threshold_gate(dot, T)
print(f'Activation: {activation}')

Activation: 0


In [35]:
input_size = 4

import numpy as np
import pandas as pd


In [36]:
class MCPNeuron(object):
  def __init__(self, w = [1,1], t = 1, gates= False):
        self.w = np.array(w)
        self.t = t
        self.gates = gates

  def predict(self, message):
        x = message
        sum_ = np.inner(self.w,x)
        if not self.gates:
          if sum_ >= self.t:
              return "Activation : 1" , "Neuron Fires"
          else:
              return "Activation : 0" , "Neuron doesn't Fire"
        else:
          if sum_ >= self.t:
              return 1
          else:
              return 0

In [50]:
np.random.seed(seed=0)
X = np.random.choice([0,1], input_size)
W = np.random.choice([-1,1], input_size)
print(f'Input vector:{X}, Weight vector:{W}')

mcp_neuron = MCPNeuron(W, t=2)


mcp_neuron.predict(X)

Input vector:[0 1 1 0], Weight vector:[1 1 1 1]


('Activation : 1', 'Neuron Fires')

In [38]:
def TruthTable(object, input, input_labels, output_labels):
    table = pd.DataFrame(input, columns = input_labels)

    out_signals = []
    for row in input:
        signal = object.predict(message = row)
        out_signals.append(signal)

    table[output_labels] = pd.Series(out_signals)
    return table

In [39]:
in_labels = ['x1', 'x2']
out_label = 'y'
in_signals = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [40]:
print(in_signals)


[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [41]:
or_weights = np.array([1,1])
or_threshold = 1
print(f'Weights: {or_weights} \nThreshold: {or_threshold}')

Weights: [1 1] 
Threshold: 1


In [42]:
OR = MCPNeuron(or_weights, or_threshold, "True")
OR_table = TruthTable(OR, in_signals, in_labels, out_label)
print(OR_table)

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1


In [43]:
in_labels = ['x1', 'x2']
out_label = 'y'
in_signals = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [44]:
print(in_signals)


[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [45]:
and_weights = np.array([1,1])
and_threshold = 2
print(f'Weights: {and_weights} \nThreshold: {and_threshold}')

Weights: [1 1] 
Threshold: 2


In [46]:
AND = MCPNeuron(and_weights, and_threshold, "True")
AND_table = TruthTable(AND, in_signals, in_labels, out_label)
print(AND_table)

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1


In [47]:
in_labels = ['x1', 'x2']
out_label = 'y'
in_signals = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [48]:
print(in_signals)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [49]:
nor_weights = np.array([-1,-1])

nor_threshold = 0
print(f'Weights: {nor_weights} \nThreshold: {nor_threshold}')

NOR = MCPNeuron(nor_weights, nor_threshold, "True")
NOR_table = TruthTable(NOR, in_signals, in_labels, out_label)
print(NOR_table)

Weights: [-1 -1] 
Threshold: 0
   x1  x2  y
0   0   0  1
1   0   1  0
2   1   0  0
3   1   1  0
